# Generated by Django 5.1.1 on 2024-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_p_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
