# Generated by Django 5.1.1 on 2024-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_tables_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='occasion',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='person',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='preference',
            field=models.CharField(default='no_preference', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
