# Generated by Django 5.1.1 on 2024-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_payment_method',
            field=models.CharField(blank=True, default='Card', max_length=50, null=True),
        ),
    ]
